---
title: "DCC-GARCH"
output: pdf_document
---



```{r}
library(rmgarch)
library(rugarch)
```

```{r}
# GARCH(1,1) specification
garch11.spec = ugarchspec(mean.model = list(armaOrder = c(0,0)),variance.model = list(garchOrder = c(1,1), model = "sGARCH"),distribution.model = "norm")
garch11.spec
```

```{r}
# DCC specification
dcc.garch11.spec = dccspec(uspec = multispec(replicate(2,garch11.spec)),dccOrder = c(1,1),distribution = "mvnorm")
dcc.garch11.spec
```

```{r}
canada = read.csv('Canada dataset.csv')
date_ca = canada$Date
sptsx = canada$SPTSX
wti_ca = canada$WTI
covid_new_ca = canada$NEW_CASE
covid_total_ca = canada$CUM_CASE
sr = canada$sr[1:3343]
cr = canada$cr[1:3343]
```

```{r}
library(ggplot2)
library(dplyr)
library(patchwork) 

# 
data <- data.frame(day = as.Date(date_ca), stock = sptsx, commodity = wti_ca)
p1 <- ggplot(data, aes(x=day, y=stock)) +
  geom_line(size = 0.2) +
  ggtitle('Stock Market') +
  xlab('time') +
  ylab('SP/TSX')
p2 <- ggplot(data, aes(x=day, y=commodity)) +
  geom_line(size = 0.2) +
  ggtitle('Commodity Market') +
  xlab('time') +
  ylab('Crude Oil')
p1 + p2
```

```{r}
data <- data.frame(day = as.Date(date_ca[2:3344]), stock = sr, commodity = cr)
p1 <- ggplot(data, aes(x=day, y=stock)) +
  geom_line(size = 0.1) +
  ggtitle('Stock Market Return') +
  xlab('time') +
  ylab('SP/TSX')
p2 <- ggplot(data, aes(x=day, y=commodity)) +
  geom_line(size = 0.1) +
  ggtitle('Commodity Market Return') +
  xlab('time') +
  ylab('Crude Oil')
p1 + p2
```

```{r}
dcc.fit_ca = dccfit(dcc.garch11.spec,data=data.frame(stock = sr, commodity = cr))
correlation_ca = unname(rcor(dcc.fit_ca, type = 'R')[1,2,])
plot(as.ts(correlation_ca), ylab = 'Conditional Correlation')
```

```{r}
cov_ca = unname(rcov(dcc.fit_ca)[1,2,])
vol_stock_ca = unname(rcov(dcc.fit_ca)[1,1,])
vol_commo_ca = unname(rcov(dcc.fit_ca)[2,2,])
new_ca = covid_new_ca[2:3344]
cum_ca = covid_total_ca[2:3344]
ca_data = data.frame(date_ca[2:3344],correlation_ca,cov_ca,vol_stock_ca,vol_commo_ca,new_ca,cum_ca)
write.csv(ca_data,'correlation_ca.csv')
```

```{r}
plot(as.ts(vol_stock_ca), ylab = 'Volatility SP/TSX')
plot(as.ts(vol_commo_ca), ylab = 'Volatility Crude Oil')
```


```{r}
data <- data.frame(day = as.Date(date_ca[3236:3344]), new = covid_new_ca[3236:3344])
p1 <- ggplot(data, aes(x=day, y=new)) +
  geom_line(color = 'black', size = 0.5) +
  ggtitle('daily new case') 
p1
```

```{r}
diff_new <- diff(covid_new_ca[3236:3344])
plot(as.ts(diff_new))
adf.test(diff_new)
model.build=function(p){
  return(dlmModPoly(2,dV=p[1],dW=p[2:3]))
}
model.mle1=dlmMLE(diff_new,parm = c(0.1,0,1,1),
                 build = model.build)
#if(model.mle1$convergence==0) print("converged") else print("did not converge")
model.mle1$par
model.fit1 <- model.build(model.mle1$par)
model.filtered1 <- dlmFilter(diff_new, model.fit1)
n <- 5
model.forecast <- dlmForecast(model.filtered1, nAhead=n)
a <- drop(model.forecast$a%*%t(FF(model.fit1)))
df <- data.frame(x=c(1:5), y=a, series="forecast")
g.dlm <- ggplot(df, aes(x=x, y=y, colour=series)) + 
  geom_line()
g.dlm
```

```{r}
forecast_case = c()
num = 0
cum = covid_new_ca[3344]
for (i in a) {
  num = num + 1
  cum = floor(cum + i)
  forecast_case[num] = cum
}
```

```{r}
dcc.fcst_ca = dccforecast(dcc.fit_ca,n.ahead = 5)
cov_df = rcov(dcc.fcst_ca)
vol_stock_ca_fcst = unname(cov_df$`1979-02-25 19:00:00`[1,1,])
vol_commo_ca_fcst = unname(cov_df$`1979-02-25 19:00:00`[2,2,])
```

```{r}
ca_forecast_case = data.frame(forecast_case,vol_stock_ca_fcst,vol_commo_ca_fcst)
write.csv(ca_forecast_case,'forecast_ca.csv')
```

