---
title: "Untitled"
output: pdf_document
---

```{r}
library(rmgarch)
library(rugarch)
```

```{r}
# GARCH(1,1) specification
garch11.spec = ugarchspec(mean.model = list(armaOrder = c(0,0)),variance.model = list(garchOrder = c(1,1), model = "sGARCH"),distribution.model = "norm")
garch11.spec
```

```{r}
# DCC specification
dcc.garch11.spec = dccspec(uspec = multispec(replicate(2,garch11.spec)),dccOrder = c(1,1),distribution = "mvnorm")
dcc.garch11.spec
```

```{r}
au = read.csv('AU dataset.csv')
date_au = au$Date
spasx = au$SPASX
wti_au = au$WTI
covid_new_au = au$NEW_CASE
covid_total_au = au$CUM_CASE
sr = au$sr[1:3321]
cr = au$cr[1:3321]
```

```{r}
library(ggplot2)
library(dplyr)
library(patchwork) 

# 
data <- data.frame(day = as.Date(date_au), stock = spasx, commodity = wti_au)
p1 <- ggplot(data, aes(x=day, y=stock)) +
  geom_line(color = 'green', size = 0.2) +
  ggtitle('Stock Market') 
p2 <- ggplot(data, aes(x=day, y=commodity)) +
  geom_line(color = 'blue', size = 0.2) +
  ggtitle('Commodity Market') 
p1 + p2
```

```{r}
data <- data.frame(day = as.Date(date_au), stock = sr, commodity = cr)
p1 <- ggplot(data, aes(x=day, y=stock)) +
  geom_line(size = 0.1) +
  ggtitle('Stock Market Return') +
  xlab('time') +
  ylab('SP/ASX')
p2 <- ggplot(data, aes(x=day, y=commodity)) +
  geom_line(size = 0.1) +
  ggtitle('Commodity Market Return') +
  xlab('time') +
  ylab('Crude Oil')
p1 + p2
```

```{r}
dcc.fit_au = dccfit(dcc.garch11.spec,data=data.frame(stock = sr, commodity = cr))
correlation_au = unname(rcor(dcc.fit_au, type = 'R')[1,2,])
plot(as.ts(correlation_au), ylab = 'Conditional Correlation')
```

```{r}
cov_au = unname(rcov(dcc.fit_au)[1,2,])
vol_stock_au = unname(rcov(dcc.fit_au)[1,1,])
vol_commo_au = unname(rcov(dcc.fit_au)[2,2,])
new_au = covid_new_au
cum_au = covid_total_au
au_data = data.frame(date_au,correlation_au,cov_au,vol_stock_au,vol_commo_au,new_au,cum_au)
write.csv(au_data,'correlation_au.csv')
```

```{r}
plot(as.ts(vol_stock_au), ylab = 'Volatility SP/ASX')
plot(as.ts(vol_commo_au), ylab = 'Volatility Crude Oil')
```

```{r}
diff_new <- covid_new_au[3217:3321]
plot(as.ts(diff_new))
adf.test(diff_new)
model.build=function(p){
  return(dlmModPoly(2,dV=p[1],dW=p[2:3]))
}
model.mle1=dlmMLE(diff_new,parm = c(0.1,0,1,1),
                 build = model.build)

model.mle1$par
model.fit1 <- model.build(model.mle1$par)
model.filtered1 <- dlmFilter(diff_new, model.fit1)

n <- 5
model.forecast <- dlmForecast(model.filtered1, nAhead=n)
a <- drop(model.forecast$a%*%t(FF(model.fit1)))
df <- data.frame(x=c(1:5), y=a, series="forecast")
g.dlm <- ggplot(df, aes(x=x, y=y, colour=series)) + 
  geom_line()
g.dlm

forecast_case = floor(a)
```


```{r}
dcc.fcst_au = dccforecast(dcc.fit_au,n.ahead = 5)
cov_df = rcov(dcc.fcst_au)
vol_stock_au_fcst = unname(cov_df$`1979-02-03 19:00:00`[1,1,])
vol_commo_au_fcst = unname(cov_df$`1979-02-03 19:00:00`[2,2,])
```

```{r}
au_forecast_case = data.frame(forecast_case,vol_stock_au_fcst,vol_commo_au_fcst)
write.csv(au_forecast_case,'forecast_au.csv')
```

